### ISSUE TITLE
Apply for membership

### ISSUE THREAD

**Issue by milivojm** [ivansipek/roster-ui#3]
Any person can apply for membership in Roster. 

Mandatory fields:
- username

Optional field:
- e-mail

**Comment by milivojm** [comment]
On `Login` page - rename `Register` to `Apply for Membership` and link it to `Apply for Membership` page.

**Comment by ivansipek** [comment]
Mandatory fields:
-username
-First name
-email

Optional fields:
-phone number
-Last name
-age

**Comment by ivansipek** [comment]
I forgot, but I will add password and repeat password field of course.

**Comment by milivojm** [comment]
Ok, can you please put labels next to input fields too?

**Comment by milivojm** [comment]
Feel free to use Bootstrap CSS if that is easier for you.

**Comment by ivansipek** [comment]
I added labels.
